name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
      name: Build and Test
      timeout-minutes: 60
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: oven-sh/setup-bun@v1
 
        - name: Install dependencies 🧳
          run: bun install

        - name: Install Playwright Browsers 🕹️
          run: bunx playwright install --with-deps

        - name: Check Lint 💅🏻
          run: bun run lint && bun run typecheck

        - name: Run Build 🔨
          run: bun run build
 
        - name: Run Tests 🧪
          run: bun run e2e:test
        
          
